apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ include "redis.fullname" . }}-app
  ports:
  - port: 6379
    targetPort: 6379
